Fix order of cd and patch.

diff --git a/get_sources_funs b/get_sources_funs
--- a/get_sources_funs
+++ b/get_sources_funs
@@ -95,8 +95,8 @@ getclipper() {
     else
         echo "Checking out clipper (gemmi branch)"
         git clone -b gemmi https://ccp4forge.rc-harwell.ac.uk/ccp4/clipper.git || fail "Failed to clone clipper"
-        patch -p1 < ../../patches/clipper-gemmi075.patch || fail "Failed to patch clipper"
         cd clipper
+        patch -p1 < ../../patches/clipper-gemmi075.patch || fail "Failed to patch clipper"
         echo
     fi
     echo
